name: weather_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  loader_overlay: ^2.0.6
  flutter_bloc: ^8.0.1
  stream_transform: ^2.0.0
  firebase_auth: ^3.3.19
  google_fonts: ^3.0.0
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  shared_preferences: ^2.0.15
  syncfusion_flutter_charts: ^20.2.36

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  generate: true

